### ISSUE TITLE
CANguru Bridge doesn't work with newer Olimex hardware due to wrong CAN baudrate

### ISSUE THREAD

**Issue by Axelli2** [CANguru-System/10-Aktuelle-OTA-Versionen#3]
Olimex ESP32-EVA boards are using a newer version of ESP32 controller now.
In this version an additional configuration bit is available to divide CAN baudrate by 2.
Because this is not considered in current software for the CANguru bridge, real CAN baudrate is 125kbs instead of needed 250kbs.
My quick fix is to configure 500kbs and it works.
For future use CAN driver should consider different versions of ESP32 controller to set baudrate correctly.

**Comment by CANguru-System** [comment]
Hello Axelli2,
thank you for your info. I was not aware of that. So I switched the CAN-driver.
Regards 
Gustav

**Comment by Axelli2** [comment]
New CAN driver works with newest OLIMEX hardware.
Thanks Gustav

**Comment by Axelli2** [comment]
New CAN driver works with newest OLIMEX hardware.
Thanks Gustav
