### ISSUE TITLE
CANguru-Bridge-Olimex- Version 2.3 doesn't compile

### ISSUE THREAD

**Issue by Axelli2** [CANguru-System/10-Aktuelle-OTA-Versionen#4]
it seems to be that some defines are missing

#######################################################
Compiling .pio\build\esp32-evb\lib135\FS\vfs_api.cpp.o
src/main.cpp: In function 'void produceFrame(patterns)':
src/main.cpp:292:20: error: 'ReadConfig' was not declared in this scope
     M_PATTERN[1] = ReadConfig;
                    ^
src/main.cpp:335:20: error: 'sendCntLokBuffer' was not declared in this scope
     M_PATTERN[1] = sendCntLokBuffer;
                    ^
src/main.cpp:338:20: error: 'sendLokBuffer' was not declared in this scope
     M_PATTERN[1] = sendLokBuffer;
                    ^
src/main.cpp: In function 'void proc_fromGW2CANandClnt()':
src/main.cpp:539:10: error: 'ReadConfig' was not declared in this scope
     case ReadConfig:
          ^
src/main.cpp:540:10: error: 'WriteConfig' was not declared in this scope
     case WriteConfig:
          ^
src/main.cpp:560:10: error: 'sendCntLokBuffer_R' was not declared in this scope
     case sendCntLokBuffer_R:
          ^
src/main.cpp:580:10: error: 'sendLokBuffer_R' was not declared in this scope
     case sendLokBuffer_R:
          ^
src/main.cpp: In function 'void proc_fromCAN2SYSandGW()':
src/main.cpp:784:10: error: 'LokDiscovery_R' was not declared in this scope
     case LokDiscovery_R:
          ^
src/main.cpp:792:10: error: 'MFXVerify' was not declared in this scope
     case MFXVerify:
          ^
src/main.cpp:803:10: error: 'ReadConfig_R' was not declared in this scope
     case ReadConfig_R:
          ^
src/main.cpp:830:10: error: 'SWITCH_ACC_R' was not declared in this scope
     case SWITCH_ACC_R:
          ^
src/main.cpp:845:10: error: 'WriteConfig_R' was not declared in this scope
     case WriteConfig_R:
          ^
Archiving .pio\build\esp32-evb\lib18f\libAsyncTCP.a
Compiling .pio\build\esp32-evb\lib5d3\WiFi\ETH.cpp.o
*** [.pio\build\esp32-evb\src\main.cpp.o] Error 1

**Comment by CANguru-System** [comment]
Hello Axelli2,
sorry, my fault. I updated the repository. It should work now. If not, please tell me.
Regards 
Gustav

**Comment by Axelli2** [comment]
Hi Gustav
if i exchange the file CANguruDefs.h only in my repository, I can compile it successfuly.
But to make it usable for others you have to add the CAN driver again. It got lost due to issue #3;-)
Regards
Axel

**Comment by Axelli2** [comment]
Hi Gustav
I just recognized that you are using the Expressive CAN driver now. Forget my post 43 minutes ago.
regards
Axel
